### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by magick93** [david-martin/keycloak-with-openshift-auth-provider#1]
Hello

Does `keycloak-with-openshift-auth-provider` allow new users to register as OpenShift users?

Currently I add and remove usesr to my OpenShift cluster using the cli and `HTPasswdPasswordIdentityProvider` and would like something more enterprise-y.

Thanks

**Comment by david-martin** [comment]
Hi @magick93.
Apologies for the slow response.

If you wish to use keycloak for managing OpenShift users (the opposite of what this is for), you can configurate keycloak as an identity provider in OpenShift https://docs.openshift.com/container-platform/3.11/install_config/configuring_authentication.html#identity-providers-configuring
